package database

import (
	"database/sql"
	"log"
)

func RunMigrations() {
	if postgresDB != nil {
		migratePostgreSQL(postgresDB)
		transactionMigration(postgresDB)
	}
}

func migratePostgreSQL(db *sql.DB) {
	createUsersTable := `
    CREATE TABLE IF NOT EXISTS public.users
    (
        id_user SERIAL PRIMARY KEY,
        usercode VARCHAR(255),
        email VARCHAR(255),
        fnamet VARCHAR(255),
        lnamet VARCHAR(255),
        fnamee VARCHAR(255),
        lnamee VARCHAR(255),
        password TEXT NOT NULL,
        provider VARCHAR(100),
        provider_id TEXT,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
    );
    
    CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
    CREATE INDEX IF NOT EXISTS idx_users_usercode ON public.users(usercode);
    
    COMMENT ON TABLE public.users IS 'เป็น Tables สำหรับเก็บข้อมูลของ ผู้ใช้';
    `
	// CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
	// CREATE INDEX IF NOT EXISTS idx_users_usercode ON public.users(usercode);
	// เป็นการเพิ่มดัชนี (Index) บนคอลัมน์ email และ usercode ในตาราง users เพื่อเพิ่มประสิทธิภาพในการค้นหาข้อมูลตามคอลัมน์เหล่านี้
	_, err := db.Exec(createUsersTable)
	if err != nil {
		log.Fatalf("Error creating users table: %v", err)
	}
	log.Println("✓ Users table migrated successfully")
}

func transactionMigration(db *sql.DB) {
	createTypeTransactionsTable := `
    CREATE TABLE IF NOT EXISTS public.type_transactions
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nametypet VARCHAR(255) NOT NULL,
        nametypee VARCHAR(255) NOT NULL
    );
    
    COMMENT ON TABLE public.type_transactions IS 'เป็น Tables สำหรับเก็บประเภทของธุรกรรม';
    `

	createCategoryTable := `
    CREATE TABLE IF NOT EXISTS public.category
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name_categoryt VARCHAR(255) NOT NULL,
        name_categorye VARCHAR(255) NOT NULL
    );
    
    COMMENT ON TABLE public.category IS 'เป็น Tables สำหรับเก็บหมวดหมู่ของธุรกรรม';
    `

	createTransactionsTable := `
    CREATE TABLE IF NOT EXISTS public.transactions
    (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_user INT NOT NULL,
        id_type INT NOT NULL,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        amount DECIMAL(10,2) NOT NULL,
        id_category INT NOT NULL,
        other_category_name VARCHAR(255),
        transaction_date DATE NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        FOREIGN KEY (id_user) REFERENCES public.users(id_user),
        FOREIGN KEY (id_type) REFERENCES public.type_transactions(id),
        FOREIGN KEY (id_category) REFERENCES public.category(id)
    );
    
    CREATE INDEX IF NOT EXISTS idx_transactions_id_user ON public.transactions(id_user);
    CREATE INDEX IF NOT EXISTS idx_transactions_transaction_date ON public.transactions(transaction_date);
    
    COMMENT ON TABLE public.transactions IS 'เป็น Tables สำหรับเก็บข้อมูลธุรกรรมทางการเงิน';
    `

	ALTER_id_type_category_table := `
    ALTER TABLE category
ADD COLUMN IF NOT EXISTS id_type INT;
`

	// ✅ เพิ่ม Comment อธิบายคอลัมน์
	addColumnComment := `
    COMMENT ON COLUMN category.id_type IS 'ประเภทของหมวดหมู่ (1=รายรับ, 2=รายจ่าย)';
    `
	var err error
	// Create type_transactions table
	_, err = db.Exec(createTypeTransactionsTable)
	if err != nil {
		log.Fatalf("Error creating type_transactions table: %v", err)
	}
	log.Println("✓ Type_transactions table migrated successfully")

	// Create category table
	_, err = db.Exec(createCategoryTable)
	if err != nil {
		log.Fatalf("Error creating category table: %v", err)
	}
	log.Println("✓ Category table migrated successfully")

	// Create transactions table with foreign keys
	_, err = db.Exec(createTransactionsTable)
	if err != nil {
		log.Fatalf("Error creating transactions table: %v", err)
	}
	log.Println("✓ Transactions table migrated successfully")

	_, err = db.Exec(ALTER_id_type_category_table)
	if err != nil {
		log.Fatalf("Error ALTER TABLE category ADD COLUMN id_type: %v", err)
	}
	log.Println("✓ Transactions ALTER TABLE category ADD COLUMN id_type successfully")
	// ✅ เพิ่ม Comment
	_, err = db.Exec(addColumnComment)
	if err != nil {
		log.Printf("Warning: Could not add column comment: %v", err)
	} else {
		log.Println("✓ Column comment added successfully")
	}
}
